### ISSUE TITLE
Comparison to Refined

### ISSUE THREAD

**Issue by Swoorup** [gbwey/predicate-typed#1]
Was looking for something that supported Refine types with auto derive to JSON. 

Looks interesting at a glance. How is this similar to the refined library?

**Comment by gbwey** [comment]
Hi Swoorup,

The Predicate.Refined is similar to the refined library 'Refine' where you
only have one type 'a'
Additionally, however, predicate-typed provides the following benefits:
    1. on error it displays a detailed annotated tree of all the
calculations and exactly where the error occurred
    2. a dsl (Predicate.Prelude) that has a multitude of type level
expressions and combinators that you can leverage.
    3. Refined2 and Refined3 are more powerful than Refined (allows you to
have different input and output types)

test/TestJson shows examples of using json with Refined and Refined3: they
have FromJSON and ToJSON instances defined.

There is an example reading in a string value and then converting
internally to ip4 address (ie 4 ints between 0 and 255)  and if at any
point there is an error it shows a detailed tree of the failure and steps
leading up to it.

If you give me a specific example of what you want to achieve I can try to
give you more information or a working example.

Best,
Grant
